### ISSUE TITLE
Image in Email

### ISSUE THREAD

**Issue by StevenDJackson** [Strategery-Inc/magento-actions-in-inbox#1]
I am not always seeing the store logo in reply emails to customers. I am getting this URL as the image source:

https://ci3.googleusercontent.com/proxy/ZJ8hOPtgcUNjfSsw2M6_rGy1v3DQoEmiuzBnaJ-XYz2j1lpF6CKb7Rh4rdrHCocD_WSH9GUegVkgDSzWG5nl8GiGMdJRielTEqOTJh89gWbNOt1vWnXKNcVDu0zG9jo=s0-d-e1-ft#https://tugasunwear.com/skin/adminhtml/base/default/images/logo_email.gif

We have our entire site on HTTPS - not sure if this matters.

Also, I do see the image when admin receives email notifactions with image source:
https://d2oikkvb1s8ld7.cloudfront.net/cdn/517214/media/email/logo/stores/1/header_logo_tugasunwear.png

We are using CloudFront from Amazon to host our /media and /js folders

This is a Magento 1.8.1 install

**Comment by StevenDJackson** [comment]
my apologies, this was to a different developer

**Comment by gsomoza** [comment]
No problem. If you ever need an extra hand with Magento feel free to contact us ;)
